#server:
#  port: 8090
#spring:
#  application:
#    name: lanka-gateway
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848
#      config:
#        server-addr: 127.0.0.1:8848
#    gateway:
#      enabled: true #表明gateway开启服务注册和发现的功能，并且spring cloud gateway自动根据服务发现为每一个服务创建了一个router，这个router将以服务名开头的请求路径转发到对应的服务。
#      discovery:
#        locator:
#          lower-case-service-id: true  #是将请求路径上的服务名配置为小写（因为服务注册的时候，向注册中心注册时将服务名转成大写的了），比如以/service-hi/*的请求路径被路由转发到服务名为service-hi的服务上。
#      routes:
#        # Add your routes here.
#        - id: aliyun_route
#          uri: https://www.aliyun.com/
#          predicates:
#            - Path=/product/**
#        - id: httpbin_route
#          uri: https://httpbin.org
#          predicates:
#            - Path=/httpbin/**
#          filters:
#            - RewritePath=/httpbin/(?<segment>.*), /$\{segment}
#    sentinel:
#      transport:
#        dashboard: localhost:8011
#      datasource:
#        ds1:
#          nacos:
#            data-id: gateway.json
#            data-type: json
#            rule-type: flow