#server:
#  port: 9090
##########################################################################
##
## 配置数据源信息
##
##########################################################################
#spring:
#  application:
#    name: lanka-fastfds
#  cloud:
#    nacos:
#      config:
#        server-addr: 127.0.0.1:8848
#
##########################################################################
##
## fdfs 配置
##
##########################################################################
#fdfs:
#  connect-timeout: 5000 # 连接的超时时间
#  so-timeout: 5000 # 读取的超时时间
#  tracker-list: 192.168.64.137:22122 # tracker服务所在的ip地址和端口号
#
