#server:
#  port: 8086
##########################################################################
##
## 配置数据源信息
##
##########################################################################
#spring:
#  datasource:                                     # 数据源的相关配置
#    type: com.zaxxer.hikari.HikariDataSource      # 数据源类型：HikariCP
#    driver-class-name: com.mysql.jdbc.Driver    # mysql驱动
#    url: jdbc:mysql://127.0.0.1:3306/eat_shop?useSSL=false&serverTimezone=UTC
#    username: root
#    password: 你的密码
#    hikari:
#      connection-timeout: 30000            # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException，默认：30秒
#      minimum-idle: 5                      # 最小连接
#      maximum-pool-size: 20               # 最大连接
#      auto-commit: true                   # 自动提交
#      idle-timeout: 600000                # 连接超时的最大时长（毫秒），超时则被释放（retired），默认：10分钟
#      pool-name: DateSourceHikariCP       # 连接池名字
#      max-lifetime: 1800000              #  连接的生命时长（毫秒），超时而且没被使用则被释放，默认：30分钟
#      connection-test-query: SELECT 1
#  servlet:
#    multipart:
#      max-file-size: 512000 # 文件上传大小限制为500kb = 500 * 1024
#      max-request-size: 512000 # 请求大小限制为500kb
#  application:
#    name: lanka-common
#    cloud:
#      nacos:
#        config:
#          server-addr: 127.0.0.1:8848
##########################################################################
##
## mybatis 配置
##
##########################################################################
##mybatis:
##  type-aliases-package: com.zzm.pojo            # 所有POJO类所在包路径
##  mapper-locations: classpath:mapper/*.mapper      # mapper映射文件
#  # configuration:
#  #  log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#
#
##########################################################################
##
## mybatis mapper配置
##
##########################################################################
##mapper:
##  mappers: com.zzm.my.mapper.MyMapper
##  not-empty: false
##  identity: MYSQL
##分页插件配置
#pagehelper:
#  helper-dialect: mysql
#  support-methods-arguments: true
#
